services:
  postgres:
    container_name: backend-postgres
    image: postgres:17-alpine
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db:/app/backend/db
    restart: always

volumes:
  pgdata: